# This file was generated by GoReleaser. DO NOT EDIT.
cask "bc-cli" do
  name "bc-cli"
  desc "Butler Coffee CLI - Discover coffee knowledge and manage subscriptions from your terminal"
  homepage "https://github.com/ButlerCoffee/bc-cli"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v#{version}/bc-cli-darwin-amd64"
      sha256 "5cbf531a3283e8140eb92b1906579dcfeb125f398c2ec59b75778be09ebcc768"
      binary "bc-cli-darwin-amd64", target: "bc-cli"
    end
    on_arm do
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v#{version}/bc-cli-darwin-arm64"
      sha256 "20e019de190dcb7ab4b2b51b6fa67a24788900358fc5d9941fd086ef3224d3bf"
      binary "bc-cli-darwin-arm64", target: "bc-cli"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v#{version}/bc-cli-linux-amd64"
      sha256 "919a607a110d984520b7c4d737eb448e5c47c7db960332745db64c90ff033dd2"
      binary "bc-cli-linux-amd64", target: "bc-cli"
    end
    on_arm do
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v#{version}/bc-cli-linux-arm64"
      sha256 "c0e921693daa1ce1f39d1a565a8dd0d5b99dc3ad52f1f383158432f62c36986b"
      binary "bc-cli-linux-arm64", target: "bc-cli"
    end
  end

  # No zap stanza required
end
