# This file was generated by GoReleaser. DO NOT EDIT.
cask "bc-cli" do
  name "bc-cli"
  desc "Butler Coffee CLI - Discover coffee knowledge and manage subscriptions from your terminal"
  homepage "https://github.com/ButlerCoffee/bc-cli"
  version "1.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v#{version}/bc-cli-darwin-amd64"
      sha256 "ee41c9a58b4b4055e9db3cb87e3cb11f3b47e162dd1cba4cc1e90f64dba6149b"
      binary "bc-cli-darwin-amd64", target: "bc-cli"
    end
    on_arm do
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v#{version}/bc-cli-darwin-arm64"
      sha256 "3ff724eb94b3cc7de5ca79f8fa496c0d49db8e23fbe8b456c68909d76d580aa4"
      binary "bc-cli-darwin-arm64", target: "bc-cli"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v#{version}/bc-cli-linux-amd64"
      sha256 "57ed90c08d9f450d5d8ac1a9cf3ffc0121dceaee5854fbe4e0e00a0408f68568"
      binary "bc-cli-linux-amd64", target: "bc-cli"
    end
    on_arm do
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v#{version}/bc-cli-linux-arm64"
      sha256 "38fd42129b08a46feb07f94037f544676114338a40b913423f696ea79f45d7b4"
      binary "bc-cli-linux-arm64", target: "bc-cli"
    end
  end

  # No zap stanza required
end
