# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BcCli < Formula
  desc "Butler Coffee CLI - Discover coffee knowledge and manage subscriptions from your terminal"
  homepage "https://github.com/ButlerCoffee/bc-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v1.1.0/bc-cli-darwin-amd64"
      sha256 "751f93b3cbb390a345404bf03ab7b4affb0c1ff5bfcfb76059c724042113ba81"

      def install
        bin.install "bc-cli-darwin-amd64" => "bc-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v1.1.0/bc-cli-darwin-arm64"
      sha256 "5cd67c65e509afb175a03a00b74eacf89ebf16e48966faca344f63d59391d2f3"

      def install
        bin.install "bc-cli-darwin-arm64" => "bc-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v1.1.0/bc-cli-linux-amd64"
      sha256 "3e8b9b298191e7202a6e62ba434902bd8f1e955f2b86930ff7006682ba698517"
      def install
        bin.install "bc-cli-linux-amd64" => "bc-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ButlerCoffee/bc-cli/releases/download/v1.1.0/bc-cli-linux-arm64"
      sha256 "67c3c3f64873c72e309e3c078d3728cdc106f570da71980274b24acb7a16c290"
      def install
        bin.install "bc-cli-linux-arm64" => "bc-cli"
      end
    end
  end

  test do
    assert_match "bc-cli version", shell_output("#{bin}/bc-cli --version")
  end
end
